buildscript {
    ext.kotlin_version = "1.9.22"
    ext {
        compileSdkVersion = 34
        targetSdkVersion = 34
        minSdkVersion = 21
        ndkVersion = "26.1.10909125"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.4"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.gms:google-services:4.4.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                if (namespace == null) {
                    namespace project.group
                }
                compileSdkVersion 35
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
